### ISSUE TITLE
Land Ownership Project View default extent in QRV is too zoomed out

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#571]
When opening the Land Ownership project view, the scale is so large that it's difficult to understand what you're looking at. The small area of blue is the hydrology for the project, which also comes in for this project view. Would it be possible to have this open at the extent of the hydrology layers instead of the land ownership layers?

![image](https://user-images.githubusercontent.com/73311751/231906026-81bb5a4b-6d09-45fe-bdeb-aada86943549.png)

**Comment by joewheaton** [comment]
@jtgilbert and @philipbaileynar I thought we were clipping this down 👇 n this version? Maybe we clip it to a rectangular pad around the HUC4?

**Comment by jtgilbert** [comment]
This should be solved, is this the v 1.4.1 project?

**Comment by lauren-herbine** [comment]
I am looking at a 1.4.1 project and this is still an issue:
![image](https://user-images.githubusercontent.com/73319684/232170482-5abe3562-4949-4c3d-99fb-08af79761d4e.png)
This is [0514020102](https://warehouse.riverscapes.net/rv/be9dfa93-b2ac-40a4-9787-c6c8c250c7c6)
In a different 1.4.1 project, it has been fixed:
![image](https://user-images.githubusercontent.com/73319684/232170875-56b9e342-8cfb-4199-9fd4-6f126fddd891.png)

**Comment by joewheaton** [comment]
Good catch @lauren-herbine. @jtgilbert and @philipbaileynar we have two bigger related issues to Land Ownership:

1. For Eastern US private is not mapped as such and is showing up as "Other" and this hideous yellow.  Business logic should be fixed to reflect this (@leallysmith can you make a ticket)?
2. We need to discuss what overall clipping mask we want. I don't like this buffer around the HUC.

**Comment by jtgilbert** [comment]
@joewheaton proposed, for selecting and clipping vector layers, to use a buffered bounding box of the HUC8 so that the layers encompass enough area beyond the HUC10 to be useful for contextual maps.
